// Code generated by MockGen. DO NOT EDIT.
// Source: ./go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go

// Package txthrottler is a generated GoMock package.
package txthrottler

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"

	discovery "vitess.io/vitess/go/vt/discovery"
	throttlerdata "vitess.io/vitess/go/vt/proto/throttlerdata"
	topodata "vitess.io/vitess/go/vt/proto/topodata"
)

// MockThrottlerInterface is a mock of ThrottlerInterface interface.
type MockThrottlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockThrottlerInterfaceMockRecorder
}

// MockThrottlerInterfaceMockRecorder is the mock recorder for MockThrottlerInterface.
type MockThrottlerInterfaceMockRecorder struct {
	mock *MockThrottlerInterface
}

// NewMockThrottlerInterface creates a new mock instance.
func NewMockThrottlerInterface(ctrl *gomock.Controller) *MockThrottlerInterface {
	mock := &MockThrottlerInterface{ctrl: ctrl}
	mock.recorder = &MockThrottlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThrottlerInterface) EXPECT() *MockThrottlerInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockThrottlerInterface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockThrottlerInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockThrottlerInterface)(nil).Close))
}

// GetConfiguration mocks base method.
func (m *MockThrottlerInterface) GetConfiguration() *throttlerdata.Configuration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfiguration")
	ret0, _ := ret[0].(*throttlerdata.Configuration)
	return ret0
}

// GetConfiguration indicates an expected call of GetConfiguration.
func (mr *MockThrottlerInterfaceMockRecorder) GetConfiguration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfiguration", reflect.TypeOf((*MockThrottlerInterface)(nil).GetConfiguration))
}

// LastMaxLagNotIgnoredForTabletType mocks base method.
func (m *MockThrottlerInterface) LastMaxLagNotIgnoredForTabletType(tabletType topodata.TabletType) uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastMaxLagNotIgnoredForTabletType", tabletType)
	ret0, _ := ret[0].(uint32)
	return ret0
}

// LastMaxLagNotIgnoredForTabletType indicates an expected call of LastMaxLagNotIgnoredForTabletType.
func (mr *MockThrottlerInterfaceMockRecorder) LastMaxLagNotIgnoredForTabletType(tabletType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastMaxLagNotIgnoredForTabletType", reflect.TypeOf((*MockThrottlerInterface)(nil).LastMaxLagNotIgnoredForTabletType), tabletType)
}

// MaxRate mocks base method.
func (m *MockThrottlerInterface) MaxRate() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxRate")
	ret0, _ := ret[0].(int64)
	return ret0
}

// MaxRate indicates an expected call of MaxRate.
func (mr *MockThrottlerInterfaceMockRecorder) MaxRate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxRate", reflect.TypeOf((*MockThrottlerInterface)(nil).MaxRate))
}

// RecordReplicationLag mocks base method.
func (m *MockThrottlerInterface) RecordReplicationLag(time time.Time, ts *discovery.LegacyTabletStats) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordReplicationLag", time, ts)
}

// RecordReplicationLag indicates an expected call of RecordReplicationLag.
func (mr *MockThrottlerInterfaceMockRecorder) RecordReplicationLag(time, ts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordReplicationLag", reflect.TypeOf((*MockThrottlerInterface)(nil).RecordReplicationLag), time, ts)
}

// ResetConfiguration mocks base method.
func (m *MockThrottlerInterface) ResetConfiguration() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetConfiguration")
}

// ResetConfiguration indicates an expected call of ResetConfiguration.
func (mr *MockThrottlerInterfaceMockRecorder) ResetConfiguration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetConfiguration", reflect.TypeOf((*MockThrottlerInterface)(nil).ResetConfiguration))
}

// SetMaxRate mocks base method.
func (m *MockThrottlerInterface) SetMaxRate(rate int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMaxRate", rate)
}

// SetMaxRate indicates an expected call of SetMaxRate.
func (mr *MockThrottlerInterfaceMockRecorder) SetMaxRate(rate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxRate", reflect.TypeOf((*MockThrottlerInterface)(nil).SetMaxRate), rate)
}

// ThreadFinished mocks base method.
func (m *MockThrottlerInterface) ThreadFinished(threadID int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ThreadFinished", threadID)
}

// ThreadFinished indicates an expected call of ThreadFinished.
func (mr *MockThrottlerInterfaceMockRecorder) ThreadFinished(threadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ThreadFinished", reflect.TypeOf((*MockThrottlerInterface)(nil).ThreadFinished), threadID)
}

// Throttle mocks base method.
func (m *MockThrottlerInterface) Throttle(threadID int) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Throttle", threadID)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Throttle indicates an expected call of Throttle.
func (mr *MockThrottlerInterfaceMockRecorder) Throttle(threadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Throttle", reflect.TypeOf((*MockThrottlerInterface)(nil).Throttle), threadID)
}

// UpdateConfiguration mocks base method.
func (m *MockThrottlerInterface) UpdateConfiguration(configuration *throttlerdata.Configuration, copyZeroValues bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfiguration", configuration, copyZeroValues)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfiguration indicates an expected call of UpdateConfiguration.
func (mr *MockThrottlerInterfaceMockRecorder) UpdateConfiguration(configuration, copyZeroValues interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfiguration", reflect.TypeOf((*MockThrottlerInterface)(nil).UpdateConfiguration), configuration, copyZeroValues)
}
